<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::insert(
            array(
                array('id' => '1101','province_id' => '11','name' => 'KABUPATEN SIMEULUE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1102','province_id' => '11','name' => 'KABUPATEN ACEH SINGKIL' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1103','province_id' => '11','name' => 'KABUPATEN ACEH SELATAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1104','province_id' => '11','name' => 'KABUPATEN ACEH TENGGARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1105','province_id' => '11','name' => 'KABUPATEN ACEH TIMUR' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1106','province_id' => '11','name' => 'KABUPATEN ACEH TENGAH' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1107','province_id' => '11','name' => 'KABUPATEN ACEH BARAT' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1108','province_id' => '11','name' => 'KABUPATEN ACEH BESAR' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1109','province_id' => '11','name' => 'KABUPATEN PIDIE' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1110','province_id' => '11','name' => 'KABUPATEN BIREUEN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1111','province_id' => '11','name' => 'KABUPATEN ACEH UTARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1112','province_id' => '11','name' => 'KABUPATEN ACEH BARAT DAYA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1113','province_id' => '11','name' => 'KABUPATEN GAYO LUES' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1114','province_id' => '11','name' => 'KABUPATEN ACEH TAMIANG' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1115','province_id' => '11','name' => 'KABUPATEN NAGAN RAYA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1116','province_id' => '11','name' => 'KABUPATEN ACEH JAYA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1117','province_id' => '11','name' => 'KABUPATEN BENER MERIAH' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1118','province_id' => '11','name' => 'KABUPATEN PIDIE JAYA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1171','province_id' => '11','name' => 'KOTA BANDA ACEH' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1172','province_id' => '11','name' => 'KOTA SABANG' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1173','province_id' => '11','name' => 'KOTA LANGSA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1174','province_id' => '11','name' => 'KOTA LHOKSEUMAWE' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1175','province_id' => '11','name' => 'KOTA SUBULUSSALAM' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1201','province_id' => '12','name' => 'KABUPATEN NIAS' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1202','province_id' => '12','name' => 'KABUPATEN MANDAILING NATAL' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1203','province_id' => '12','name' => 'KABUPATEN TAPANULI SELATAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1204','province_id' => '12','name' => 'KABUPATEN TAPANULI TENGAH' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1205','province_id' => '12','name' => 'KABUPATEN TAPANULI UTARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1206','province_id' => '12','name' => 'KABUPATEN TOBA SAMOSIR' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1207','province_id' => '12','name' => 'KABUPATEN LABUHAN BATU' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1208','province_id' => '12','name' => 'KABUPATEN ASAHAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1209','province_id' => '12','name' => 'KABUPATEN SIMALUNGUN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1210','province_id' => '12','name' => 'KABUPATEN DAIRI' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1211','province_id' => '12','name' => 'KABUPATEN KARO' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1212','province_id' => '12','name' => 'KABUPATEN DELI SERDANG' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1213','province_id' => '12','name' => 'KABUPATEN LANGKAT' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1214','province_id' => '12','name' => 'KABUPATEN NIAS SELATAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1215','province_id' => '12','name' => 'KABUPATEN HUMBANG HASUNDUTAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1216','province_id' => '12','name' => 'KABUPATEN PAKPAK BHARAT' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1217','province_id' => '12','name' => 'KABUPATEN SAMOSIR' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1218','province_id' => '12','name' => 'KABUPATEN SERDANG BEDAGAI' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1219','province_id' => '12','name' => 'KABUPATEN BATU BARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1220','province_id' => '12','name' => 'KABUPATEN PADANG LAWAS UTARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1221','province_id' => '12','name' => 'KABUPATEN PADANG LAWAS' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1222','province_id' => '12','name' => 'KABUPATEN LABUHAN BATU SELATAN' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1223','province_id' => '12','name' => 'KABUPATEN LABUHAN BATU UTARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1224','province_id' => '12','name' => 'KABUPATEN NIAS UTARA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1225','province_id' => '12','name' => 'KABUPATEN NIAS BARAT' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1271','province_id' => '12','name' => 'KOTA SIBOLGA' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1272','province_id' => '12','name' => 'KOTA TANJUNG BALAI' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1273','province_id' => '12','name' => 'KOTA PEMATANG SIANTAR' , 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1274','province_id' => '12','name' => 'KOTA TEBING TINGGI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1275','province_id' => '12','name' => 'KOTA MEDAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1276','province_id' => '12','name' => 'KOTA BINJAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1277','province_id' => '12','name' => 'KOTA PADANGSIDIMPUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1278','province_id' => '12','name' => 'KOTA GUNUNGSITOLI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1301','province_id' => '13','name' => 'KABUPATEN KEPULAUAN MENTAWAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1302','province_id' => '13','name' => 'KABUPATEN PESISIR SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1303','province_id' => '13','name' => 'KABUPATEN SOLOK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1304','province_id' => '13','name' => 'KABUPATEN SIJUNJUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1305','province_id' => '13','name' => 'KABUPATEN TANAH DATAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1306','province_id' => '13','name' => 'KABUPATEN PADANG PARIAMAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1307','province_id' => '13','name' => 'KABUPATEN AGAM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1308','province_id' => '13','name' => 'KABUPATEN LIMA PULUH KOTA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1309','province_id' => '13','name' => 'KABUPATEN PASAMAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1310','province_id' => '13','name' => 'KABUPATEN SOLOK SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1311','province_id' => '13','name' => 'KABUPATEN DHARMASRAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1312','province_id' => '13','name' => 'KABUPATEN PASAMAN BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1371','province_id' => '13','name' => 'KOTA PADANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1372','province_id' => '13','name' => 'KOTA SOLOK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1373','province_id' => '13','name' => 'KOTA SAWAH LUNTO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1374','province_id' => '13','name' => 'KOTA PADANG PANJANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1375','province_id' => '13','name' => 'KOTA BUKITTINGGI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1376','province_id' => '13','name' => 'KOTA PAYAKUMBUH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1377','province_id' => '13','name' => 'KOTA PARIAMAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1401','province_id' => '14','name' => 'KABUPATEN KUANTAN SINGINGI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1402','province_id' => '14','name' => 'KABUPATEN INDRAGIRI HULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1403','province_id' => '14','name' => 'KABUPATEN INDRAGIRI HILIR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1404','province_id' => '14','name' => 'KABUPATEN PELALAWAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1405','province_id' => '14','name' => 'KABUPATEN S I A K', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1406','province_id' => '14','name' => 'KABUPATEN KAMPAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1407','province_id' => '14','name' => 'KABUPATEN ROKAN HULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1408','province_id' => '14','name' => 'KABUPATEN BENGKALIS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1409','province_id' => '14','name' => 'KABUPATEN ROKAN HILIR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1410','province_id' => '14','name' => 'KABUPATEN KEPULAUAN MERANTI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1471','province_id' => '14','name' => 'KOTA PEKANBARU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1473','province_id' => '14','name' => 'KOTA D U M A I', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1501','province_id' => '15','name' => 'KABUPATEN KERINCI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1502','province_id' => '15','name' => 'KABUPATEN MERANGIN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1503','province_id' => '15','name' => 'KABUPATEN SAROLANGUN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1504','province_id' => '15','name' => 'KABUPATEN BATANG HARI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1505','province_id' => '15','name' => 'KABUPATEN MUARO JAMBI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1506','province_id' => '15','name' => 'KABUPATEN TANJUNG JABUNG TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1507','province_id' => '15','name' => 'KABUPATEN TANJUNG JABUNG BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1508','province_id' => '15','name' => 'KABUPATEN TEBO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1509','province_id' => '15','name' => 'KABUPATEN BUNGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1571','province_id' => '15','name' => 'KOTA JAMBI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1572','province_id' => '15','name' => 'KOTA SUNGAI PENUH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1601','province_id' => '16','name' => 'KABUPATEN OGAN KOMERING ULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1602','province_id' => '16','name' => 'KABUPATEN OGAN KOMERING ILIR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1603','province_id' => '16','name' => 'KABUPATEN MUARA ENIM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1604','province_id' => '16','name' => 'KABUPATEN LAHAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1605','province_id' => '16','name' => 'KABUPATEN MUSI RAWAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1606','province_id' => '16','name' => 'KABUPATEN MUSI BANYUASIN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1607','province_id' => '16','name' => 'KABUPATEN BANYU ASIN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1608','province_id' => '16','name' => 'KABUPATEN OGAN KOMERING ULU SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1609','province_id' => '16','name' => 'KABUPATEN OGAN KOMERING ULU TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1610','province_id' => '16','name' => 'KABUPATEN OGAN ILIR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1611','province_id' => '16','name' => 'KABUPATEN EMPAT LAWANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1612','province_id' => '16','name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1613','province_id' => '16','name' => 'KABUPATEN MUSI RAWAS UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1671','province_id' => '16','name' => 'KOTA PALEMBANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1672','province_id' => '16','name' => 'KOTA PRABUMULIH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1673','province_id' => '16','name' => 'KOTA PAGAR ALAM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1674','province_id' => '16','name' => 'KOTA LUBUKLINGGAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1701','province_id' => '17','name' => 'KABUPATEN BENGKULU SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1702','province_id' => '17','name' => 'KABUPATEN REJANG LEBONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1703','province_id' => '17','name' => 'KABUPATEN BENGKULU UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1704','province_id' => '17','name' => 'KABUPATEN KAUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1705','province_id' => '17','name' => 'KABUPATEN SELUMA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1706','province_id' => '17','name' => 'KABUPATEN MUKOMUKO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1707','province_id' => '17','name' => 'KABUPATEN LEBONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1708','province_id' => '17','name' => 'KABUPATEN KEPAHIANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1709','province_id' => '17','name' => 'KABUPATEN BENGKULU TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1771','province_id' => '17','name' => 'KOTA BENGKULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1801','province_id' => '18','name' => 'KABUPATEN LAMPUNG BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1802','province_id' => '18','name' => 'KABUPATEN TANGGAMUS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1803','province_id' => '18','name' => 'KABUPATEN LAMPUNG SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1804','province_id' => '18','name' => 'KABUPATEN LAMPUNG TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1805','province_id' => '18','name' => 'KABUPATEN LAMPUNG TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1806','province_id' => '18','name' => 'KABUPATEN LAMPUNG UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1807','province_id' => '18','name' => 'KABUPATEN WAY KANAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1808','province_id' => '18','name' => 'KABUPATEN TULANGBAWANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1809','province_id' => '18','name' => 'KABUPATEN PESAWARAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1810','province_id' => '18','name' => 'KABUPATEN PRINGSEWU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1811','province_id' => '18','name' => 'KABUPATEN MESUJI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1812','province_id' => '18','name' => 'KABUPATEN TULANG BAWANG BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1813','province_id' => '18','name' => 'KABUPATEN PESISIR BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1871','province_id' => '18','name' => 'KOTA BANDAR LAMPUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1872','province_id' => '18','name' => 'KOTA METRO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1901','province_id' => '19','name' => 'KABUPATEN BANGKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1902','province_id' => '19','name' => 'KABUPATEN BELITUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1903','province_id' => '19','name' => 'KABUPATEN BANGKA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1904','province_id' => '19','name' => 'KABUPATEN BANGKA TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1905','province_id' => '19','name' => 'KABUPATEN BANGKA SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1906','province_id' => '19','name' => 'KABUPATEN BELITUNG TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '1971','province_id' => '19','name' => 'KOTA PANGKAL PINANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2101','province_id' => '21','name' => 'KABUPATEN KARIMUN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2102','province_id' => '21','name' => 'KABUPATEN BINTAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2103','province_id' => '21','name' => 'KABUPATEN NATUNA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2104','province_id' => '21','name' => 'KABUPATEN LINGGA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2105','province_id' => '21','name' => 'KABUPATEN KEPULAUAN ANAMBAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2171','province_id' => '21','name' => 'KOTA B A T A M', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '2172','province_id' => '21','name' => 'KOTA TANJUNG PINANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3101','province_id' => '31','name' => 'KABUPATEN KEPULAUAN SERIBU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3171','province_id' => '31','name' => 'KOTA JAKARTA SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3172','province_id' => '31','name' => 'KOTA JAKARTA TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3173','province_id' => '31','name' => 'KOTA JAKARTA PUSAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3174','province_id' => '31','name' => 'KOTA JAKARTA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3175','province_id' => '31','name' => 'KOTA JAKARTA UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3201','province_id' => '32','name' => 'KABUPATEN BOGOR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3202','province_id' => '32','name' => 'KABUPATEN SUKABUMI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3203','province_id' => '32','name' => 'KABUPATEN CIANJUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3204','province_id' => '32','name' => 'KABUPATEN BANDUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3205','province_id' => '32','name' => 'KABUPATEN GARUT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3206','province_id' => '32','name' => 'KABUPATEN TASIKMALAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3207','province_id' => '32','name' => 'KABUPATEN CIAMIS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3208','province_id' => '32','name' => 'KABUPATEN KUNINGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3209','province_id' => '32','name' => 'KABUPATEN CIREBON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3210','province_id' => '32','name' => 'KABUPATEN MAJALENGKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3211','province_id' => '32','name' => 'KABUPATEN SUMEDANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3212','province_id' => '32','name' => 'KABUPATEN INDRAMAYU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3213','province_id' => '32','name' => 'KABUPATEN SUBANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3214','province_id' => '32','name' => 'KABUPATEN PURWAKARTA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3215','province_id' => '32','name' => 'KABUPATEN KARAWANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3216','province_id' => '32','name' => 'KABUPATEN BEKASI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3217','province_id' => '32','name' => 'KABUPATEN BANDUNG BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3218','province_id' => '32','name' => 'KABUPATEN PANGANDARAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3271','province_id' => '32','name' => 'KOTA BOGOR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3272','province_id' => '32','name' => 'KOTA SUKABUMI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3273','province_id' => '32','name' => 'KOTA BANDUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3274','province_id' => '32','name' => 'KOTA CIREBON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3275','province_id' => '32','name' => 'KOTA BEKASI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3276','province_id' => '32','name' => 'KOTA DEPOK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3277','province_id' => '32','name' => 'KOTA CIMAHI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3278','province_id' => '32','name' => 'KOTA TASIKMALAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3279','province_id' => '32','name' => 'KOTA BANJAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3301','province_id' => '33','name' => 'KABUPATEN CILACAP', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3302','province_id' => '33','name' => 'KABUPATEN BANYUMAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3303','province_id' => '33','name' => 'KABUPATEN PURBALINGGA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3304','province_id' => '33','name' => 'KABUPATEN BANJARNEGARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3305','province_id' => '33','name' => 'KABUPATEN KEBUMEN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3306','province_id' => '33','name' => 'KABUPATEN PURWOREJO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3307','province_id' => '33','name' => 'KABUPATEN WONOSOBO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3308','province_id' => '33','name' => 'KABUPATEN MAGELANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3309','province_id' => '33','name' => 'KABUPATEN BOYOLALI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3310','province_id' => '33','name' => 'KABUPATEN KLATEN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3311','province_id' => '33','name' => 'KABUPATEN SUKOHARJO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3312','province_id' => '33','name' => 'KABUPATEN WONOGIRI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3313','province_id' => '33','name' => 'KABUPATEN KARANGANYAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3314','province_id' => '33','name' => 'KABUPATEN SRAGEN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3315','province_id' => '33','name' => 'KABUPATEN GROBOGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3316','province_id' => '33','name' => 'KABUPATEN BLORA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3317','province_id' => '33','name' => 'KABUPATEN REMBANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3318','province_id' => '33','name' => 'KABUPATEN PATI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3319','province_id' => '33','name' => 'KABUPATEN KUDUS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3320','province_id' => '33','name' => 'KABUPATEN JEPARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3321','province_id' => '33','name' => 'KABUPATEN DEMAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3322','province_id' => '33','name' => 'KABUPATEN SEMARANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3323','province_id' => '33','name' => 'KABUPATEN TEMANGGUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3324','province_id' => '33','name' => 'KABUPATEN KENDAL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3325','province_id' => '33','name' => 'KABUPATEN BATANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3326','province_id' => '33','name' => 'KABUPATEN PEKALONGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3327','province_id' => '33','name' => 'KABUPATEN PEMALANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3328','province_id' => '33','name' => 'KABUPATEN TEGAL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3329','province_id' => '33','name' => 'KABUPATEN BREBES', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3371','province_id' => '33','name' => 'KOTA MAGELANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3372','province_id' => '33','name' => 'KOTA SURAKARTA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3373','province_id' => '33','name' => 'KOTA SALATIGA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3374','province_id' => '33','name' => 'KOTA SEMARANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3375','province_id' => '33','name' => 'KOTA PEKALONGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3376','province_id' => '33','name' => 'KOTA TEGAL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3401','province_id' => '34','name' => 'KABUPATEN KULON PROGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3402','province_id' => '34','name' => 'KABUPATEN BANTUL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3403','province_id' => '34','name' => 'KABUPATEN GUNUNG KIDUL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3404','province_id' => '34','name' => 'KABUPATEN SLEMAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3471','province_id' => '34','name' => 'KOTA YOGYAKARTA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3501','province_id' => '35','name' => 'KABUPATEN PACITAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3502','province_id' => '35','name' => 'KABUPATEN PONOROGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3503','province_id' => '35','name' => 'KABUPATEN TRENGGALEK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3504','province_id' => '35','name' => 'KABUPATEN TULUNGAGUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3505','province_id' => '35','name' => 'KABUPATEN BLITAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3506','province_id' => '35','name' => 'KABUPATEN KEDIRI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3507','province_id' => '35','name' => 'KABUPATEN MALANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3508','province_id' => '35','name' => 'KABUPATEN LUMAJANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3509','province_id' => '35','name' => 'KABUPATEN JEMBER', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3510','province_id' => '35','name' => 'KABUPATEN BANYUWANGI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3511','province_id' => '35','name' => 'KABUPATEN BONDOWOSO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3512','province_id' => '35','name' => 'KABUPATEN SITUBONDO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3513','province_id' => '35','name' => 'KABUPATEN PROBOLINGGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3514','province_id' => '35','name' => 'KABUPATEN PASURUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3515','province_id' => '35','name' => 'KABUPATEN SIDOARJO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3516','province_id' => '35','name' => 'KABUPATEN MOJOKERTO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3517','province_id' => '35','name' => 'KABUPATEN JOMBANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3518','province_id' => '35','name' => 'KABUPATEN NGANJUK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3519','province_id' => '35','name' => 'KABUPATEN MADIUN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3520','province_id' => '35','name' => 'KABUPATEN MAGETAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3521','province_id' => '35','name' => 'KABUPATEN NGAWI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3522','province_id' => '35','name' => 'KABUPATEN BOJONEGORO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3523','province_id' => '35','name' => 'KABUPATEN TUBAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3524','province_id' => '35','name' => 'KABUPATEN LAMONGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3525','province_id' => '35','name' => 'KABUPATEN GRESIK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3526','province_id' => '35','name' => 'KABUPATEN BANGKALAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3527','province_id' => '35','name' => 'KABUPATEN SAMPANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3528','province_id' => '35','name' => 'KABUPATEN PAMEKASAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3529','province_id' => '35','name' => 'KABUPATEN SUMENEP', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3571','province_id' => '35','name' => 'KOTA KEDIRI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3572','province_id' => '35','name' => 'KOTA BLITAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3573','province_id' => '35','name' => 'KOTA MALANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3574','province_id' => '35','name' => 'KOTA PROBOLINGGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3575','province_id' => '35','name' => 'KOTA PASURUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3576','province_id' => '35','name' => 'KOTA MOJOKERTO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3577','province_id' => '35','name' => 'KOTA MADIUN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3578','province_id' => '35','name' => 'KOTA SURABAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3579','province_id' => '35','name' => 'KOTA BATU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3601','province_id' => '36','name' => 'KABUPATEN PANDEGLANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3602','province_id' => '36','name' => 'KABUPATEN LEBAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3603','province_id' => '36','name' => 'KABUPATEN TANGERANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3604','province_id' => '36','name' => 'KABUPATEN SERANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3671','province_id' => '36','name' => 'KOTA TANGERANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3672','province_id' => '36','name' => 'KOTA CILEGON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3673','province_id' => '36','name' => 'KOTA SERANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '3674','province_id' => '36','name' => 'KOTA TANGERANG SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5101','province_id' => '51','name' => 'KABUPATEN JEMBRANA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5102','province_id' => '51','name' => 'KABUPATEN TABANAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5103','province_id' => '51','name' => 'KABUPATEN BADUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5104','province_id' => '51','name' => 'KABUPATEN GIANYAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5105','province_id' => '51','name' => 'KABUPATEN KLUNGKUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5106','province_id' => '51','name' => 'KABUPATEN BANGLI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5107','province_id' => '51','name' => 'KABUPATEN KARANG ASEM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5108','province_id' => '51','name' => 'KABUPATEN BULELENG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5171','province_id' => '51','name' => 'KOTA DENPASAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5201','province_id' => '52','name' => 'KABUPATEN LOMBOK BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5202','province_id' => '52','name' => 'KABUPATEN LOMBOK TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5203','province_id' => '52','name' => 'KABUPATEN LOMBOK TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5204','province_id' => '52','name' => 'KABUPATEN SUMBAWA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5205','province_id' => '52','name' => 'KABUPATEN DOMPU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5206','province_id' => '52','name' => 'KABUPATEN BIMA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5207','province_id' => '52','name' => 'KABUPATEN SUMBAWA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5208','province_id' => '52','name' => 'KABUPATEN LOMBOK UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5271','province_id' => '52','name' => 'KOTA MATARAM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5272','province_id' => '52','name' => 'KOTA BIMA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5301','province_id' => '53','name' => 'KABUPATEN SUMBA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5302','province_id' => '53','name' => 'KABUPATEN SUMBA TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5303','province_id' => '53','name' => 'KABUPATEN KUPANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5304','province_id' => '53','name' => 'KABUPATEN TIMOR TENGAH SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5305','province_id' => '53','name' => 'KABUPATEN TIMOR TENGAH UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5306','province_id' => '53','name' => 'KABUPATEN BELU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5307','province_id' => '53','name' => 'KABUPATEN ALOR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5308','province_id' => '53','name' => 'KABUPATEN LEMBATA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5309','province_id' => '53','name' => 'KABUPATEN FLORES TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5310','province_id' => '53','name' => 'KABUPATEN SIKKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5311','province_id' => '53','name' => 'KABUPATEN ENDE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5312','province_id' => '53','name' => 'KABUPATEN NGADA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5313','province_id' => '53','name' => 'KABUPATEN MANGGARAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5314','province_id' => '53','name' => 'KABUPATEN ROTE NDAO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5315','province_id' => '53','name' => 'KABUPATEN MANGGARAI BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5316','province_id' => '53','name' => 'KABUPATEN SUMBA TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5317','province_id' => '53','name' => 'KABUPATEN SUMBA BARAT DAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5318','province_id' => '53','name' => 'KABUPATEN NAGEKEO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5319','province_id' => '53','name' => 'KABUPATEN MANGGARAI TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5320','province_id' => '53','name' => 'KABUPATEN SABU RAIJUA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5321','province_id' => '53','name' => 'KABUPATEN MALAKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '5371','province_id' => '53','name' => 'KOTA KUPANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6101','province_id' => '61','name' => 'KABUPATEN SAMBAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6102','province_id' => '61','name' => 'KABUPATEN BENGKAYANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6103','province_id' => '61','name' => 'KABUPATEN LANDAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6104','province_id' => '61','name' => 'KABUPATEN MEMPAWAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6105','province_id' => '61','name' => 'KABUPATEN SANGGAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6106','province_id' => '61','name' => 'KABUPATEN KETAPANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6107','province_id' => '61','name' => 'KABUPATEN SINTANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6108','province_id' => '61','name' => 'KABUPATEN KAPUAS HULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6109','province_id' => '61','name' => 'KABUPATEN SEKADAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6110','province_id' => '61','name' => 'KABUPATEN MELAWI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6111','province_id' => '61','name' => 'KABUPATEN KAYONG UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6112','province_id' => '61','name' => 'KABUPATEN KUBU RAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6171','province_id' => '61','name' => 'KOTA PONTIANAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6172','province_id' => '61','name' => 'KOTA SINGKAWANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6201','province_id' => '62','name' => 'KABUPATEN KOTAWARINGIN BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6202','province_id' => '62','name' => 'KABUPATEN KOTAWARINGIN TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6203','province_id' => '62','name' => 'KABUPATEN KAPUAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6204','province_id' => '62','name' => 'KABUPATEN BARITO SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6205','province_id' => '62','name' => 'KABUPATEN BARITO UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6206','province_id' => '62','name' => 'KABUPATEN SUKAMARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6207','province_id' => '62','name' => 'KABUPATEN LAMANDAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6208','province_id' => '62','name' => 'KABUPATEN SERUYAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6209','province_id' => '62','name' => 'KABUPATEN KATINGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6210','province_id' => '62','name' => 'KABUPATEN PULANG PISAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6211','province_id' => '62','name' => 'KABUPATEN GUNUNG MAS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6212','province_id' => '62','name' => 'KABUPATEN BARITO TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6213','province_id' => '62','name' => 'KABUPATEN MURUNG RAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6271','province_id' => '62','name' => 'KOTA PALANGKA RAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6301','province_id' => '63','name' => 'KABUPATEN TANAH LAUT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6302','province_id' => '63','name' => 'KABUPATEN KOTA BARU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6303','province_id' => '63','name' => 'KABUPATEN BANJAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6304','province_id' => '63','name' => 'KABUPATEN BARITO KUALA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6305','province_id' => '63','name' => 'KABUPATEN TAPIN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6306','province_id' => '63','name' => 'KABUPATEN HULU SUNGAI SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6307','province_id' => '63','name' => 'KABUPATEN HULU SUNGAI TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6308','province_id' => '63','name' => 'KABUPATEN HULU SUNGAI UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6309','province_id' => '63','name' => 'KABUPATEN TABALONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6310','province_id' => '63','name' => 'KABUPATEN TANAH BUMBU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6311','province_id' => '63','name' => 'KABUPATEN BALANGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6371','province_id' => '63','name' => 'KOTA BANJARMASIN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6372','province_id' => '63','name' => 'KOTA BANJAR BARU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6401','province_id' => '64','name' => 'KABUPATEN PASER', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6402','province_id' => '64','name' => 'KABUPATEN KUTAI BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6403','province_id' => '64','name' => 'KABUPATEN KUTAI KARTANEGARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6404','province_id' => '64','name' => 'KABUPATEN KUTAI TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6405','province_id' => '64','name' => 'KABUPATEN BERAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6409','province_id' => '64','name' => 'KABUPATEN PENAJAM PASER UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6411','province_id' => '64','name' => 'KABUPATEN MAHAKAM HULU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6471','province_id' => '64','name' => 'KOTA BALIKPAPAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6472','province_id' => '64','name' => 'KOTA SAMARINDA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6474','province_id' => '64','name' => 'KOTA BONTANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6501','province_id' => '65','name' => 'KABUPATEN MALINAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6502','province_id' => '65','name' => 'KABUPATEN BULUNGAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6503','province_id' => '65','name' => 'KABUPATEN TANA TIDUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6504','province_id' => '65','name' => 'KABUPATEN NUNUKAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '6571','province_id' => '65','name' => 'KOTA TARAKAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7101','province_id' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7102','province_id' => '71','name' => 'KABUPATEN MINAHASA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7103','province_id' => '71','name' => 'KABUPATEN KEPULAUAN SANGIHE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7104','province_id' => '71','name' => 'KABUPATEN KEPULAUAN TALAUD', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7105','province_id' => '71','name' => 'KABUPATEN MINAHASA SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7106','province_id' => '71','name' => 'KABUPATEN MINAHASA UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7107','province_id' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7108','province_id' => '71','name' => 'KABUPATEN SIAU TAGULANDANG BIARO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7109','province_id' => '71','name' => 'KABUPATEN MINAHASA TENGGARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7110','province_id' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7111','province_id' => '71','name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7171','province_id' => '71','name' => 'KOTA MANADO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7172','province_id' => '71','name' => 'KOTA BITUNG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7173','province_id' => '71','name' => 'KOTA TOMOHON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7174','province_id' => '71','name' => 'KOTA KOTAMOBAGU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7201','province_id' => '72','name' => 'KABUPATEN BANGGAI KEPULAUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7202','province_id' => '72','name' => 'KABUPATEN BANGGAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7203','province_id' => '72','name' => 'KABUPATEN MOROWALI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7204','province_id' => '72','name' => 'KABUPATEN POSO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7205','province_id' => '72','name' => 'KABUPATEN DONGGALA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7206','province_id' => '72','name' => 'KABUPATEN TOLI-TOLI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7207','province_id' => '72','name' => 'KABUPATEN BUOL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7208','province_id' => '72','name' => 'KABUPATEN PARIGI MOUTONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7209','province_id' => '72','name' => 'KABUPATEN TOJO UNA-UNA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7210','province_id' => '72','name' => 'KABUPATEN SIGI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7211','province_id' => '72','name' => 'KABUPATEN BANGGAI LAUT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7212','province_id' => '72','name' => 'KABUPATEN MOROWALI UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7271','province_id' => '72','name' => 'KOTA PALU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7301','province_id' => '73','name' => 'KABUPATEN KEPULAUAN SELAYAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7302','province_id' => '73','name' => 'KABUPATEN BULUKUMBA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7303','province_id' => '73','name' => 'KABUPATEN BANTAENG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7304','province_id' => '73','name' => 'KABUPATEN JENEPONTO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7305','province_id' => '73','name' => 'KABUPATEN TAKALAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7306','province_id' => '73','name' => 'KABUPATEN GOWA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7307','province_id' => '73','name' => 'KABUPATEN SINJAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7308','province_id' => '73','name' => 'KABUPATEN MAROS', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7309','province_id' => '73','name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7310','province_id' => '73','name' => 'KABUPATEN BARRU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7311','province_id' => '73','name' => 'KABUPATEN BONE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7312','province_id' => '73','name' => 'KABUPATEN SOPPENG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7313','province_id' => '73','name' => 'KABUPATEN WAJO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7314','province_id' => '73','name' => 'KABUPATEN SIDENRENG RAPPANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7315','province_id' => '73','name' => 'KABUPATEN PINRANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7316','province_id' => '73','name' => 'KABUPATEN ENREKANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7317','province_id' => '73','name' => 'KABUPATEN LUWU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7318','province_id' => '73','name' => 'KABUPATEN TANA TORAJA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7322','province_id' => '73','name' => 'KABUPATEN LUWU UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7325','province_id' => '73','name' => 'KABUPATEN LUWU TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7326','province_id' => '73','name' => 'KABUPATEN TORAJA UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7371','province_id' => '73','name' => 'KOTA MAKASSAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7372','province_id' => '73','name' => 'KOTA PAREPARE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7373','province_id' => '73','name' => 'KOTA PALOPO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7401','province_id' => '74','name' => 'KABUPATEN BUTON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7402','province_id' => '74','name' => 'KABUPATEN MUNA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7403','province_id' => '74','name' => 'KABUPATEN KONAWE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7404','province_id' => '74','name' => 'KABUPATEN KOLAKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7405','province_id' => '74','name' => 'KABUPATEN KONAWE SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7406','province_id' => '74','name' => 'KABUPATEN BOMBANA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7407','province_id' => '74','name' => 'KABUPATEN WAKATOBI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7408','province_id' => '74','name' => 'KABUPATEN KOLAKA UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7409','province_id' => '74','name' => 'KABUPATEN BUTON UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7410','province_id' => '74','name' => 'KABUPATEN KONAWE UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7411','province_id' => '74','name' => 'KABUPATEN KOLAKA TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7412','province_id' => '74','name' => 'KABUPATEN KONAWE KEPULAUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7413','province_id' => '74','name' => 'KABUPATEN MUNA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7414','province_id' => '74','name' => 'KABUPATEN BUTON TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7415','province_id' => '74','name' => 'KABUPATEN BUTON SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7471','province_id' => '74','name' => 'KOTA KENDARI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7472','province_id' => '74','name' => 'KOTA BAUBAU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7501','province_id' => '75','name' => 'KABUPATEN BOALEMO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7502','province_id' => '75','name' => 'KABUPATEN GORONTALO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7503','province_id' => '75','name' => 'KABUPATEN POHUWATO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7504','province_id' => '75','name' => 'KABUPATEN BONE BOLANGO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7505','province_id' => '75','name' => 'KABUPATEN GORONTALO UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7571','province_id' => '75','name' => 'KOTA GORONTALO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7601','province_id' => '76','name' => 'KABUPATEN MAJENE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7602','province_id' => '76','name' => 'KABUPATEN POLEWALI MANDAR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7603','province_id' => '76','name' => 'KABUPATEN MAMASA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7604','province_id' => '76','name' => 'KABUPATEN MAMUJU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7605','province_id' => '76','name' => 'KABUPATEN MAMUJU UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '7606','province_id' => '76','name' => 'KABUPATEN MAMUJU TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8101','province_id' => '81','name' => 'KABUPATEN MALUKU TENGGARA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8102','province_id' => '81','name' => 'KABUPATEN MALUKU TENGGARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8103','province_id' => '81','name' => 'KABUPATEN MALUKU TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8104','province_id' => '81','name' => 'KABUPATEN BURU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8105','province_id' => '81','name' => 'KABUPATEN KEPULAUAN ARU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8106','province_id' => '81','name' => 'KABUPATEN SERAM BAGIAN BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8107','province_id' => '81','name' => 'KABUPATEN SERAM BAGIAN TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8108','province_id' => '81','name' => 'KABUPATEN MALUKU BARAT DAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8109','province_id' => '81','name' => 'KABUPATEN BURU SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8171','province_id' => '81','name' => 'KOTA AMBON', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8172','province_id' => '81','name' => 'KOTA TUAL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8201','province_id' => '82','name' => 'KABUPATEN HALMAHERA BARAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8202','province_id' => '82','name' => 'KABUPATEN HALMAHERA TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8203','province_id' => '82','name' => 'KABUPATEN KEPULAUAN SULA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8204','province_id' => '82','name' => 'KABUPATEN HALMAHERA SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8205','province_id' => '82','name' => 'KABUPATEN HALMAHERA UTARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8206','province_id' => '82','name' => 'KABUPATEN HALMAHERA TIMUR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8207','province_id' => '82','name' => 'KABUPATEN PULAU MOROTAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8208','province_id' => '82','name' => 'KABUPATEN PULAU TALIABU', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8271','province_id' => '82','name' => 'KOTA TERNATE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '8272','province_id' => '82','name' => 'KOTA TIDORE KEPULAUAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9101','province_id' => '91','name' => 'KABUPATEN FAKFAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9102','province_id' => '91','name' => 'KABUPATEN KAIMANA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9103','province_id' => '91','name' => 'KABUPATEN TELUK WONDAMA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9104','province_id' => '91','name' => 'KABUPATEN TELUK BINTUNI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9105','province_id' => '91','name' => 'KABUPATEN MANOKWARI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9106','province_id' => '91','name' => 'KABUPATEN SORONG SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9107','province_id' => '91','name' => 'KABUPATEN SORONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9108','province_id' => '91','name' => 'KABUPATEN RAJA AMPAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9109','province_id' => '91','name' => 'KABUPATEN TAMBRAUW', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9110','province_id' => '91','name' => 'KABUPATEN MAYBRAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9111','province_id' => '91','name' => 'KABUPATEN MANOKWARI SELATAN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9112','province_id' => '91','name' => 'KABUPATEN PEGUNUNGAN ARFAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9171','province_id' => '91','name' => 'KOTA SORONG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9401','province_id' => '94','name' => 'KABUPATEN MERAUKE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9402','province_id' => '94','name' => 'KABUPATEN JAYAWIJAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9403','province_id' => '94','name' => 'KABUPATEN JAYAPURA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9404','province_id' => '94','name' => 'KABUPATEN NABIRE', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9408','province_id' => '94','name' => 'KABUPATEN KEPULAUAN YAPEN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9409','province_id' => '94','name' => 'KABUPATEN BIAK NUMFOR', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9410','province_id' => '94','name' => 'KABUPATEN PANIAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9411','province_id' => '94','name' => 'KABUPATEN PUNCAK JAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9412','province_id' => '94','name' => 'KABUPATEN MIMIKA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9413','province_id' => '94','name' => 'KABUPATEN BOVEN DIGOEL', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9414','province_id' => '94','name' => 'KABUPATEN MAPPI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9415','province_id' => '94','name' => 'KABUPATEN ASMAT', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9416','province_id' => '94','name' => 'KABUPATEN YAHUKIMO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9417','province_id' => '94','name' => 'KABUPATEN PEGUNUNGAN BINTANG', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9418','province_id' => '94','name' => 'KABUPATEN TOLIKARA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9419','province_id' => '94','name' => 'KABUPATEN SARMI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9420','province_id' => '94','name' => 'KABUPATEN KEEROM', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9426','province_id' => '94','name' => 'KABUPATEN WAROPEN', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9427','province_id' => '94','name' => 'KABUPATEN SUPIORI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9428','province_id' => '94','name' => 'KABUPATEN MAMBERAMO RAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9429','province_id' => '94','name' => 'KABUPATEN NDUGA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9430','province_id' => '94','name' => 'KABUPATEN LANNY JAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9431','province_id' => '94','name' => 'KABUPATEN MAMBERAMO TENGAH', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9432','province_id' => '94','name' => 'KABUPATEN YALIMO', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9433','province_id' => '94','name' => 'KABUPATEN PUNCAK', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9434','province_id' => '94','name' => 'KABUPATEN DOGIYAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9435','province_id' => '94','name' => 'KABUPATEN INTAN JAYA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9436','province_id' => '94','name' => 'KABUPATEN DEIYAI', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')),
                array('id' => '9471','province_id' => '94','name' => 'KOTA JAYAPURA', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s'))
            )
        );
    }
}
